### PR TITLE
HAAR-436 Add Missing STCs

### PR DESCRIPTION
**Pull request by karenmillermoj**

### CODE REVIEW

**Review by AlTurner-MOJ — COMMENTED** [review]
Did you intend to use STC2 and STC3 as the Prison IDs?
Looks like Oakhill address using Rainsbrook prison_id

**Comment by karenmillermoj** [comment]
> Did you intend to use STC2 and STC3 as the Prison IDs? Looks like Oakhill address using Rainsbrook prison_id

**Comment by karenmillermoj** [comment]
Good spot - yes, cut and paste error.  Had a chat with Mike, although these aren't in the prison api as prisons we do store them for probation and their ids match those.   Will fix typo

**Review by AlTurner-MOJ — APPROVED** [review]
lgtm

**Pull request merged**
